export const SMARTSCHOOL_ERROR_CODES: Record<number, string> = {
	1: 'The surname must be at least 2 characters long.',
	2: 'The first name must be at least 2 characters long.',
	3: 'The username must be at least 2 characters long.',
	4: 'The new password is not complex enough. See SmartSchool password rules.',
	5: 'No group has been selected.',
	6: 'The username already exists.',
	7: 'The passwords do not match.',
	8: 'The specified web services password is incorrect.',
	9: 'This user does not exist.',
	10: 'An error occurred while processing the data. Nothing was applied.',
	11: 'An error occurred while saving the class data.',
	12: 'This user does not exist.',
	13: 'An error occurred while copying or moving the users to the specified class.',
	14: 'Insufficient data provided.',
	15: 'Duplicate username.',
	16: 'Duplicate internal number.',
	17: 'An error occurred while saving one or more profile fields.',
	18: 'An error occurred while sending the message.',
	19: 'Parent ID does not exist.',
	20: 'Failed to add the course.',
	21: 'A course with the same name already exists.',
	22: 'Course not found.',
	23: 'An unknown error occurred during processing.',
	24: 'A user with this internal number already exists. Please enter another number.',
	25: 'Warning: the user could not be modified because they do not exist in Smartschool.',
	26: 'Warning: the user could not be added because they already exist in Smartschool.',
	27: 'Warning: the institution number is not present in Smartschool. Please add the institution first.',
	28: 'Selecting a base role is mandatory.',
	29: 'You are no longer allowed to change the base role of this account.',
	30: 'Only students may be members of official classes.',
	31: 'The student may be a member of only one official class.',
	32: 'A student must be a member of one official class.',
	33: 'Recording the class change failed.',
	34: 'The student cannot be activated because they are not a member of an official class.',
	35: 'The institution number is mandatory for an official class.',
	36: 'You are not allowed to change the type of an official class.',
	37: 'You are not allowed to change the type of this class or group because some members are not students.',
	38: 'You are not allowed to change the type of this class or group because some members are already in another official class.',
	39: 'You must select a training component.',
	40: 'You may no longer change a class name.',
	41: 'You may no longer change the administrative number.',
	42: 'You may no longer change the institution number.',
	43: 'You may no longer change the training component.',
	44: 'The training component is mandatory.',
	45: 'You are not allowed to change the type of a class.',
	46: 'You must select the type of the group.',
	47: 'A class with the same unique class or group code already exists.',
	48: 'The internal number already exists.',
	49: 'The date is not valid.',
	50: "The 'Skore' module is not activated.",
	51: 'An error occurred while unenrolling the student.',
	52: 'This password is not allowed. Please choose another password.',
	53: 'The parent group was not found.',
	54: 'The parent group may not be an official class.',
	55: 'An official class cannot contain subgroups.',
	56: 'Please provide a valid date for the school year.',
	57: "The 'Timetable code' must be unique. The value you entered is already in use.",
};
